Resources:
  Function:
    Type: AWS::Serverless::Function
    Properties:
      Timeout: 300
      MemorySize: 128
      Handler: dist/index.handler
      CodeUri: /home/shane/repo/market-deal-importer
      Runtime: nodejs16.x
      Architectures:
      - x86_64
    Metadata:
      SamResourceId: Function
